# Generated by Django 3.2.12 on 2022-03-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='School_class',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='School_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_stepik',
        ),
    ]
