# Generated by Django 3.2.12 on 2022-04-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zion', '0003_main_linkes'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_sun_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('name_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zion.main_linkes')),
            ],
        ),
    ]
