# Generated by Django 3.2.12 on 2022-04-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zion', '0004_main_sun_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_sun_menu',
            new_name='main_sub_menu',
        ),
    ]
