# Generated by Django 3.2.12 on 2022-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zion', '0005_rename_main_sun_menu_main_sub_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_sub_menu',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
